@startuml

node PC{
[Browser] #fff
}
node Frontend_Server{
component SecondaryStudyMakerFrontend_Angular{
  [angularCode]
  database LocalStorage
}

Browser<->Frontend_Server

angularCode--LocalStorage
@enduml